### ISSUE TITLE
Returned values include xml markup

### ISSUE THREAD

**Issue by pano9000** [bitinix/VIES-VAT#2]
Hello,

Just tried out the current version from npm (`1.2.2`) and noticed that the response output by vies-vat includes some XML markup, that shouldn't be there:

```
{
  error: false,
  viesInfo: {
    valid: true,
    countryCode: '<ns2:countryCode>XX</ns2:countryCode>',
    vatNumber: '<ns2:vatNumber>123456</ns2:vatNumber>',
    requestDate: '<ns2:requestDate>2023-01-26+01:00</ns2:requestDate>',
    name: '<ns2:name>---</ns2:name>',
    address: '<ns2:address>---</ns2:address>'
  }
}
```

Kind regards,

**Comment by bitinix** [comment]
Thanks for letting me know. I'll fix that today & let you know.

**Comment by bitinix** [comment]
1.2.4 Pushed
Try again please

**Comment by bitinix** [comment]
var viesVat = require("vies-vat")

debugTest()
async function debugTest() {
  var viesOptions = {
        "countryCode": "EL",
        "vatNumber": '090029757',
        "timeout": 60000, 
        "debug": true
      }
  var res = await viesVat(viesOptions)
  if (res.error) console.log('vies debug test - error ', res.error)
  console.log('vies debug test Result ', res.viesInfo)
}

Output
vies debug - Request to VIES Starting
vies debug - status:200 Successful call 
vies debug - Request to VIES Completed
vies debug test Result  {
  valid: true,
  countryCode: 'EL',
  vatNumber: '090029757',
  requestDate: '2023-01-26+01:00',
  name: 'ΔΗΜΟΤΙΚΗ ΕΠΙΧΕΙΡΗΣΗ ΥΔΡΕΥΣΗΣ ΚΑΙ ΑΠΟΧΕΤΕΥΣΗΣ ΝΗΣΟΥ ΧΙΟΥ||ΔΕΥΑΧ',
  address: 'ΔΗΜΟΚΡΑΤΙΑΣ 4         82100 - ΧΙΟΣ'
}

**Comment by pano9000** [comment]
thank you, I can confirm the issue is gone with 1.2.4
would be nice to see that updated in Github as well
